Action: Add SHA256 hash verification.

diff --git a/.github/workflows/action-test.yml b/.github/workflows/action-test.yml
--- a/.github/workflows/action-test.yml
+++ b/.github/workflows/action-test.yml
@@ -88,19 +88,18 @@ jobs:
       - run: echo "The file was downloaded to ${{ steps.download-poetry-both.outputs.file-path }}"
       - name: Test file exists
         run: python -c "import os; exit(not os.path.isfile('different_folder/new_name.py'))"
+      - run: ls different_folder && rm -r different_folder
 
       - name: Test to download a file and match MD5
         uses: ./
         id: download-tar-md5
         with:
           file-url: 'https://github.com/carlosperate/download-file-action/archive/refs/tags/v1.0.3.tar.gz'
-          location: 'other_folder'
-          file-name: 'new_name.tar.gz'
+          file-name: 'name_md5.tar.gz'
           md5: 'e3b51204dedc75588ca164a26b51610d'
-      - run: echo "The file was downloaded to ${{ steps.download-tar-md5.outputs.file-path }}"
       - name: Test file exists
-        run: python -c "import os, sys; sys.exit(not os.path.isfile('other_folder/new_name.tar.gz'))"
-      - run: ls other_folder && rm -r other_folder
+        run: python -c "import os, sys; sys.exit(not os.path.isfile('name_md5.tar.gz'))"
+      - run: rm name_md5.tar.gz
 
       - name: Test bad MD5 value
         continue-on-error: true
@@ -111,5 +110,28 @@ jobs:
           md5: '12345678901234567890123456789012'
       - name: Fail workflow if bad MD5 test didn't raise an error
         if: steps.download-tar-md5-bad.outcome == 'success'
-        run: echo "The file was downloaded to ${{ steps.download-tar-md5-bad.outcome }}"
+        run: exit 1
+      - run: rm download-file-action-1.0.3.tar.gz
+
+      - name: Test to download a file and match SHA256
+        uses: ./
+        id: download-tar-sha256
+        with:
+          file-url: 'https://github.com/carlosperate/download-file-action/archive/refs/tags/v1.0.3.tar.gz'
+          file-name: 'name_sha256.tar.gz'
+          sha256: '76ef5cf6e910a4955f713fb36cca6f90ffeee6ffafe743754716e149d68136de'
+      - name: Test file exists
+        run: python -c "import os, sys; sys.exit(not os.path.isfile('name_sha256.tar.gz'))"
+      - run: rm name_sha256.tar.gz
+
+      - name: Test bad SHA256 value
+        continue-on-error: true
+        uses: ./
+        id: download-tar-sha256-bad
+        with:
+          file-url: 'https://github.com/carlosperate/download-file-action/archive/refs/tags/v1.0.3.tar.gz'
+          sha256: '1234567890123456789012345678901234567890123456789012345678901234'
+      - name: Fail workflow if bad SHA256 test didn't raise an error
+        if: steps.download-tar-sha256-bad.outcome == 'success'
+        run: exit 1
       - run: rm download-file-action-1.0.3.tar.gz
